### ISSUE TITLE
Crates.io doc link is broken

### ISSUE THREAD

**Issue by steveklabnik** [mvdnes/spinlock-rs#15]
it points to https://mvdnes.github.io/spinlock-rs/ which seems like it'd be correct, but it 404s.

**Comment by steveklabnik** [comment]
Ah! this is actually for the older `spinlock` crate, actually.

**Comment by mvdnes** [comment]
Yes, the `spinlock` crate is deprecated in favor of the `spin` crate. I am not aware of a method to remove / redirect the old crate.
I will close this issue but feel free to comment and I may re-open/fix it.

**Comment by steveklabnik** [comment]
There isn't directly right now, though you may want to change the description to point to the new crate, and publish a version so that it gets updated. other than that, that's it

**Comment by mvdnes** [comment]
Fixed in e02bb01...16531fd7a0a4

Thank you for posting the issue! :+1:

**Comment by steveklabnik** [comment]
Awesome, glad to be of help :) Thanks again for this crate!
