### ISSUE TITLE
Use PAUSE instruction?

### ISSUE THREAD

**Issue by birkenfeld** [mvdnes/spinlock-rs#16]
In `obtain_lock`, would it make sense (on x86) to use the PAUSE instruction inside the loop? Looking at the Intel manuals, it seems to be designed for this kind of situation.

**Comment by mvdnes** [comment]
I am unsure what this instruction does. Can you provide a resource which has some details?

**Comment by birkenfeld** [comment]
(Note that I'm not at all an expert. Just trying to learn something.)

In Linux, the `cpu_relax` function used in spinlocks calls [rep; nop](http://lxr.free-electrons.com/source/arch/x86/um/asm/processor.h#L23) which is the same as PAUSE and says it's "good thing to insert into busy-wait loops".

This quote is from the Intel x86 developer's manual:

> Improves the performance of spin-wait loops. When executing a “spin-wait loop,” processors will suffer a severe performance penalty when exiting the loop because it detects a possible memory order violation. The PAUSE instruction provides a hint to the processor that the code sequence is a spin-wait loop. The processor uses this hint to avoid the memory order violation in most situations, which greatly improves processor performance. For this reason, it is recommended that a PAUSE instruction be placed in all spin-wait loops.
An additional function of the PAUSE instruction is to reduce the power consumed by a processor while executing a spin loop. A processor can execute a spin-wait loop extremely quickly, causing the processor to consume a lot of power while it waits for the resource it is spinning on to become available. Inserting a pause instruction in a spin-wait loop greatly reduces the processor’s power consumption.

**Comment by mvdnes** [comment]
Hmm seems like a good idea then. If you or anyone else would submit a pull request I would be happy to merge it.

**Comment by mvdnes** [comment]
Thanks! :+1:

**Comment by sstewartgallus** [comment]
I'm thinking of putting this functionality in the std lib itself https://github.com/rust-lang/rust/pull/40537
