### ISSUE TITLE
Once

### ISSUE THREAD

**Issue by Ericson2314** [mvdnes/spinlock-rs#19]
Like [std::sync::Once](url), except we can do better and let the closure have a return value / hand out a `&`. 

In fact I've already written https://github.com/RustOS-Fork-Holding-Ground/lazy-static-spin/blob/spin/src/lazy.rs, a good start---and I think code would have a better home here than there.

**Comment by mvdnes** [comment]
I do not think it is a problem to merge such a feature, but I would think people would like the features to be more like the ones in the standard library.

If you want to you can either submit a pull request to merge the Lazy, or to implement Once from the stdlibs (as the only modifications needed is to replace the mutex by a spinlock).

**Comment by Ericson2314** [comment]
Baring the names (which I want to change to match) isn't this bit a simple generalization of once, analogous to how wo don't need static* locks? The standard library impl is quite a bit different / more complex, but as far as I can tell that's due to blocking.

I suppose it could be implemented with a spin lock but isn't this more efficient?

**Comment by mvdnes** [comment]
It seems so, yes. Go ahead and create a PR, I will be happy to merge.
