### ISSUE TITLE
Unsafe impls

### ISSUE THREAD

**Issue by Ericson2314** [mvdnes/spinlock-rs#23]
While working on Once, I noticed that our unsafe `Send` and `Sync` impls are different from std---I am not sure why or whether its sound. [I ended up going with the RwLock ones for `Once`, since both give access to a `&T` to potentially multiple threads.] 

 - https://github.com/mvdnes/spinlock-rs/blob/master/src/mutex.rs#L95
 - https://github.com/mvdnes/spinlock-rs/blob/master/src/rw_lock.rs#L72-L73
 - https://doc.rust-lang.org/nightly/src/std/up/src/libstd/sync/mutex.rs.html#129-131
 - https://doc.rust-lang.org/nightly/src/std/up/src/libstd/sync/rwlock.rs.html#75-77

**Comment by mvdnes** [comment]
At one point, I thought I understood how `Send` and `Sync` work, but the more I read the less sure I am.
I do not really know why you would need the `Send` bound for `Mutex` to be `Sync` for example.

Also, I think `Mutex` is already `Send` when `T: Send`, but that needs to be tested.

Any thoughts on this matter would be welcome.

**Comment by Ericson2314** [comment]
I'm a bit rusty too. Last I heard `T: Sync` means its safe to share `&T` across threads, and Sync => Send.

I'd just make them match their std equivalents as I can't think of any reason why differences in implementation would matter here.

**Comment by mvdnes** [comment]
Seems like a reasonable thing to do, yes
