### ISSUE TITLE
Debug trait

### ISSUE THREAD

**Issue by arthurprs** [mvdnes/spinlock-rs#9]
I understand it's a no_std crate, but adding a Debug trait would be trivial and it'd greatly expand it's use case in non no_std projects.

**Comment by mvdnes** [comment]
Deriving Debug can be done easily here. The only thing is that both AtomicBool and UnsafeCell do not derive it, so we need to implement it on our own.

I will take a look at the Debug implementations of the stdlib Mutex and RWLock.

**Comment by arthurprs** [comment]
Thank you!
